# Generated by Django 3.2.3 on 2021-05-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=240, verbose_name='header')),
                ('subheader', models.CharField(max_length=240)),
                ('leftheader', models.CharField(max_length=240)),
                ('leftsubheader', models.CharField(max_length=240)),
                ('rightheader', models.CharField(max_length=240)),
                ('rightsubheader', models.CharField(max_length=240)),
            ],
        ),
    ]
